### ISSUE TITLE
memory error in bb() list comprehension

### ISSUE THREAD

**Issue by schwittlick** [schwittlick/cursor#16]
H:\Dropbox\CODE\cursor\venv\Scripts\python.exe H:/Dropbox/CODE/cursor/experiments/composition55.py
H:\Dropbox\CODE\cursor\cursor\data\recordings\1565088885.39372_compressed.json
H:\Dropbox\CODE\cursor\cursor\data\recordings\1565089006.12941_compressed.json
H:\Dropbox\CODE\cursor\cursor\data\recordings\1565089051.610323_compressed.json
H:\Dropbox\CODE\cursor\cursor\data\recordings\1565192530.559317_compressed.json
H:\Dropbox\CODE\cursor\cursor\data\recordings\1565277489.684606_compressed.json
Loaded 6637 paths from 5 recordings.
Loaded 14505 keys from 5 recordings.
This took 4369ms.
6598
Creating Composition #37 with offset=25
Traceback (most recent call last):
   File "H:/Dropbox/CODE/cursor/experiments/composition55.py", line 58, in <module>
     composition55(p0, p1, i)
   File "H:/Dropbox/CODE/cursor/experiments/composition55.py", line 36, in composition55
     print(coll.bb())
   File "H:\Dropbox\CODE\cursor\cursor\path.py", line 345, in bb
     mi = self.min()
   File "H:\Dropbox\CODE\cursor\cursor\path.py", line 352, in min
     miny = min(all_chained, key = lambda pos: pos.y).y
ValueError: min() arg is an empty sequence

**Comment by schwittlick** [comment]
seems to be working with current state

    H:\cursor\venv\Scripts\python.exe H:/cursor/experiments/composition55.py
    H:\cursor\data\recordings\1565088885.39372_compressed.json
    H:\cursor\data\recordings\1565089006.12941_compressed.json
    H:\cursor\data\recordings\1565089051.610323_compressed.json
    H:\cursor\data\recordings\1565192530.559317_compressed.json
    H:\cursor\data\recordings\1565277489.684606_compressed.json
    Loaded 6637 paths from 5 recordings.
    Loaded 14505 keys from 5 recordings.
    This took 3678ms.
    EntropyFilter: reduced path count from 6598 to 385
    BB(x=67.02721486688824, y=49.19416593076312, w=2042.361097633112, h=1556.6688513235713)
    Saving to H:\cursor\data\composition55\gcode\composition55_special_25.nc
    Creating image with size=(10882, 8275)
    Saving to H:\cursor\data\composition55\jpg\composition55_special_25_high2.jpg
